name: flutter_qr_app
description: A QR code reader powered by Flutter.
publish_to: 'none'
version: 1.0.2+100020

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  mobile_scanner: ^3.2.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
