name: flutter_qr_app
description: A QR code reader powered by Flutter.
publish_to: 'none'
version: 1.0.2+100020

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  mobile_scanner: ^2.1.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
